### ISSUE TITLE
minicode plugin in post text area not being recognised

### ISSUE THREAD

**Issue by namekia** [gracix/grav-plugin-minicode#1]
Noticed the new Grav plugin minicode and was anxious to try it out. I'm looking for a method for adding chunks of html into content and sidebars on various pages.
Installed via gpm and followed instructions on repo page.
Output of a simple html file in page content is merely: {{ ‘hello.html’ | minicode }}
Using grav-blog theme.
Looks like the plugin is not being recognized. Suggestions?

**Comment by chellige** [comment]
Did you enable the plugin?  Edit `user/plugins/minicode/minicode.yaml` and make sure that "enabled" is set to true.

```
enabled: true
twig_filter: true
enabled_in_admin: true
data_directory: minicodes/
check_html_dom: false
```

**Comment by gracix** [comment]
Thanks chellige ! 
namekia, can you use it ?

**Comment by namekia** [comment]
No, sorry. Unable to get the plugin to function. I have uninstalled it. Thank you.
Will explore shortcodes as a technique for adding small bits of html functionality.

**Comment by 2braincells2go** [comment]
Same issue, wondering if any ever solved this?
