### ISSUE TITLE
Not working with php

### ISSUE THREAD

**Issue by chellige** [gracix/grav-plugin-minicode#2]
This is exactly the type of solution I was looking for. Unfortunately it does not seem to be processing php. I created a simple test.html file in the user/minicodes folder with this content:

```
<html>
        <?php
        $output = "Hello World" ;
        echo "<pre>$output</pre>";
        ?>
</html>
```

And then added a `{{ 'test.html' | minicode }}` twig-tag to a page. I get the following output:

> $output"; ?>

**Comment by gracix** [comment]
chellige, thanks for your report.
This plugin can Raw output from file only. Can not compile php code. 
When you process the php in a php, security also has many problems, php that contains the error do not know what causes what.

It is assumed that such use in content.

ex) 

```
Lorem Ipsum is simply dummy text  {{ 'test.html' | minicode }} Lorem Ipsum has been the industry's
```

In test.html
    `<span> This is AD </span>`

After

```
Lorem Ipsum is simply dummy text <span> This is AD </span> Lorem Ipsum has been the industry's
```
